### ISSUE TITLE
unitegallery-tiles cannot scroll in mobile

### ISSUE THREAD

**Issue by mactrash** [collective/collective.ptg.unitegallery#1]
@Martronic-SA

The gallery can scroll by the page edge, but no reaction over the tiles.

Hope it can be fix, since the gallery look nice.

Thanks.

**Comment by Martronic-SA** [comment]
Hello,
Thanks for reporting.
Yes it's seems to be related to unitegallery javascripts imported via requirejs.
We may have to use a separate module for javascripts.

**Comment by mactrash** [comment]
@Martronic-SA thanks for your hard work, I feel so bad that i don't know to code... I will wait for your fix, many thanks.

**Comment by Martronic-SA** [comment]
Ok finally it doesn't seem to be related to requirejs but somhow to the javascript 'touchstart' event.
Adding a $('.unitegallery-container').off('touchstart'); seems to fix the problem but might break some other unitegallery functionalities...

**Comment by mactrash** [comment]
@Martronic-SA 

may I know where to add?

**Comment by Martronic-SA** [comment]
Coud you check the new version?
Be carfeul, it depends you will need to install collective.js.unitegallery now.

**Comment by Martronic-SA** [comment]
you may check also collective.tiles.unitegallery to add unitegalleries into mosaic.

**Comment by mactrash** [comment]
Thanks a lot 👍  👍  💯
