### ISSUE TITLE
None.css is missing error

### ISSUE THREAD

**Issue by mactrash** [collective/collective.ptg.unitegallery#3]
http://website.com/++resource++ptg.unitegallery/++resource++ptg.unitegallery/skins/None/None.css

Don't know why plone try to load such file, but it is not there.

**Comment by mactrash** [comment]
@Martronic-SA I don't know what the line doing, I just comment out the line in __init.py__ for temp fix. Can you spare some time to take a look?

Many thanks.

**Comment by Martronic-SA** [comment]
This should be fixed by  [commit](https://github.com/collective/collective.ptg.unitegallery/commit/d64f0202ddef74c090c548041838154f046c9a92)

**Comment by mactrash** [comment]
Thanks but it now crash when plone start up

    ConfigurationError: ('Invalid value for', 'post_handler', "ImportError: Couldn't import collective.ptg.unitegallery.setuphandlers, No module named setuphandlers")

**Comment by Martronic-SA** [comment]
Could you try new version 1.0b1 ? it depends on collective.js.unitegallery.

**Comment by mactrash** [comment]
@Martronic-SA thanks for your help, but... I just can find 1.0a5 ... can yo tell me more how can i got b1 ?

**Comment by Martronic-SA** [comment]
It was on standard pypi repository.
Now we've updated github.

**Comment by mactrash** [comment]
@Martronic-SA something strange hard to explain in the last release... some javascript mess and overlay with something broken over the screen.

Better test again the code with a clear cache browser.

Many thanks.
